reddit/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views

from redditapp import views as app_views

urlpatterns = [
        url(r'^home$', app_views.home, name='home'),
        path('redditapp/', include('redditapp.urls')),
        url(r'^login/', app_views.custom_login, name='login'),
        url(r'^logout', app_views.logout, name='logout'),
        url(r'^oauth/', include('social_django.urls', namespace='social')),
        url(r'^admin', admin.site.urls),
        url(r'^$', app_views.custom_login, name='login'),
        ]

redditapp/urls.py
from django.urls import path

from . import views

app_name = 'redditapp'

urlpatterns = [
        path('<int:question_id>/', views.detail, name='detail'),
        path('<int:question_id>/comment/', views.comment, name='comment'),
        path('ask_question', views.ask_question, name='ask_question'),
        path('add_question', views.add_question, name='add_question'),

        path('<int:question_id>/add_vote/', views.add_vote, name='add_vote'),
        ]

reddit/redditapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django import forms

class CommentForm(forms.Form):
    comments = forms.CharField(max_length = 100)

class QuestionForm(forms.Form):
    new_question = forms.CharField(max_length = 400)


class Question(models.Model):
    question_text = models.CharField(max_length=400)
    pub_date = models.DateTimeField('date published',auto_now_add=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)

class Comment(models.Model):
    comment_text =  models.CharField(max_length=100)
    auth_user =  models.ForeignKey('auth.User', on_delete=models.CASCADE)
    question_id =  models.ForeignKey('Question', on_delete=models.CASCADE)

class Vote(models.Model):
    voter = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    question_id =  models.ForeignKey('Question', on_delete=models.CASCADE)
    voted_date = models.DateTimeField('voted_date',auto_now_add=True)

# Create your models here.

redditapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django import forms


class CommentForm(forms.Form):
    comments = forms.CharField(max_length=100)


class QuestionForm(forms.Form):
    new_question = forms.CharField(max_length=400)


class Question(models.Model):
    question_text = models.CharField(max_length=400)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def is_voted(self, user):
        return self.vote_set.filter(voter=user).count() > 0


class Comment(models.Model):
    comment_text = models.CharField(max_length=100)
    auth_user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    question_id = models.ForeignKey('Question', on_delete=models.CASCADE)


class Vote(models.Model):
    voter = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    voted_date = models.DateTimeField('voted_date', auto_now_add=True)

reddit/redditapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect

from .models import Question,Comment,CommentForm,QuestionForm,Vote
from django.urls import reverse
from django.contrib.auth.views import login
from django.contrib.auth import logout as auth_logout

import pdb


from django.shortcuts import get_object_or_404, render,redirect
@login_required
def home(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
            'latest_question_list': latest_question_list,
            }
    return render(request, 'redditapp/home.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    is_voted = True if Vote.objects.filter(question_id=question, voter=request.user).count() > 0 else False

    total_vote_count =  Vote.objects.filter(question_id=question).count()
    context = {
            'question':question,
            'is_voted':is_voted,
            'total_vote_count':total_vote_count,
            }
    return render(request, 'redditapp/detail.html', context)

def comment(request,question_id):
    question = Question.objects.get(pk= question_id)

    if request.method == "POST":
      MyCommentForm = CommentForm(request.POST)

      if MyCommentForm.is_valid():
         c_text = MyCommentForm.cleaned_data['comments']
         new_comment = Comment(question_id=question, comment_text = c_text,auth_user= request.user)
         new_comment.save()
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)

def add_question(request):

    if request.method == "POST":
        MyQuestionForm =  QuestionForm(request.POST)

    if MyQuestionForm.is_valid():
        q_text = MyQuestionForm.cleaned_data['new_question']
        new_ques = Question(question_text = q_text,author = request.user)
        new_ques.save()
    return redirect('home')

def ask_question(request):

    return render(request,'redditapp/ask_question.html')

def add_vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    new_vote = Vote(question_id = question,voter = request.user)
    new_vote.save()
    next = request.POST.get('next', '/')

    return HttpResponseRedirect(next)

def custom_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/home')
    else:
        return login(request)

def logout(request):
    """Logs out user"""
    auth_logout(request)
    return HttpResponseRedirect('/login')

redditapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth.views import login
from django.contrib.auth import logout as auth_logout
from django.shortcuts import get_object_or_404, render, redirect

from redditapp.models import Question, Comment, CommentForm, QuestionForm, Vote


@login_required
def home(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
            'latest_question_list': latest_question_list,
            }
    return render(request, 'redditapp/home.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
        'is_voted': question.is_voted(request.user),
        'total_vote_count': question.vote_set.count(),
    }
    return render(request, 'redditapp/detail.html', context)


def comment(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            c_text = comment_form.cleaned_data['comments']
            Comment.objects.create(
                question_id=question,
                comment_text=c_text,
                auth_user=request.user
            )
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)


def add_question(request):
    if request.method == "POST":
        question_form = QuestionForm(request.POST)

        if question_form.is_valid():
            q_text = question_form.cleaned_data['new_question']
            Question.objects.create(question_text=q_text, author=request.user)

    return redirect('home')


def ask_question(request):
    return render(request, 'redditapp/ask_question.html')


def add_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if not question.is_voted(request.user):
        Vote.objects.create(question_id=question, voter=request.user)
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)


def custom_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/home')
    else:
        return login(request)


def logout(request):
    """Logs out user"""
    auth_logout(request)
    return HttpResponseRedirect('/login')

reddit/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
  <title>Simple Social Auth</title>
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
</head>
<body>
  <header>
    <h1>Simple Social Auth</h1>
    {% if user.is_authenticated %}
      You are signed in as <strong>{{ user.username }}</strong> /
      <a href="{% url 'home' %}">home</a> /
      <a href="{% url 'settings' %}">settings</a> /
      <a href="{% url 'password' %}">change password</a> /
      <a href="{% url 'logout' %}">logout</a>
    {% else %}
      <a href="{% url 'login' %}">login</a> /
      <a href="{% url 'signup' %}">signup</a>
    {% endif %}
    <hr>
  </header>
  <main>
    {% for message in messages %}
      <p style="color: {% if message.tags == 'success' %}green{% elif message.tags == 'error' %}red{% endif %}">
        {{ message }}
      </p>
    {% endfor %}
    {% block content %}
    {% endblock %}
  </main>
  <footer>
    <hr>
    <small>
      <a href="https://simpleisbetterthancomplex.com">simpleisbetterthancomplex.com</a> /
      <a href="https://simpleisbetterthancomplex.com/tutorial/2016/10/24/how-to-add-social-login-to-django.html">read more about this example</a>
    </small>
  </footer>
</body>
</html>

redditapp/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  </head>
  <body>
    <header>
      {% if user.is_authenticated %}
      You are signed in as <strong>{{ user.username }}</strong> /
      <a href="{% url 'home' %}">home</a> /
      <a href="{% url 'logout' %}">Logout</a>
      {% endif %}
      <hr>
    </header>
    <main>
    {% for message in messages %}
    <p style="color: {% if message.tags == 'success' %}green{% elif message.tags == 'error' %}red{% endif %}">
    {{ message }}
    </p>
    {% endfor %}
    {% block content %}
    {% endblock %}
    </main>
  </body>
</html>

redditapp/templates/redditapp/ask_question.html
{% extends 'base.html' %}

{% block content %}


<form action="{% url 'redditapp:add_question' %}" method="post">
{% csrf_token %}
    <input type="textarea" name="new_question" id="question{{ forloop.counter }}" value="{{ question.id }}" />
<input type="submit" value="ask question" />
</form>

{% endblock %}

redditapp/templates/redditapp/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'redditapp:comment' question.id %}" method="post">
  {% csrf_token %}
  {% for comment in question.comment_set.all %}
  <label for="comment{{ forloop.counter }}">{{ comment.comment_text }}</label><br />
  {% endfor %}
  <input type="textarea" name="comments" id="comment{{ forloop.counter }}" value="{{ comment.id }}" />
  <input type="hidden" name="next" value="{{ request.path }}">
  <input type="submit" value="Comment" />
</form>
<form action="{% url 'redditapp:add_vote' question.id %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ request.path }}">
  {% if is_voted %}
  <button type="button" disabled>Voted</button>
  {% else %}
  <input type="submit" value="Vote" />
  {% endif %}
</form>
<label>Total Votes: {{ total_vote_count }} </label>

{% endblock %}

redditapp/templates/redditapp/home.html
{% extends 'base.html' %}

{% block content %}
<p>Hello {{ user.username }}!</p>
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li><a href="/redditapp/{{ question.id }}/">{{ question.question_text }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No questions are available.</p>
{% endif %}
<a href="/redditapp/ask_question">Ask New Question</a>
{% endblock %}